title: Bharath M R
#logo:
description: Software Development Engineer in Test |
As a Software Development Engineer in Test (SDET) I develop and execute effective test plans, test cases, and
scripts to ensure the quality and performance of software products. I am skilled in Manual testing, API testing,
and Automation using Playwright, a modern web testing framework. I also have a deep understanding of the
technical aspects of software development, with knowledge of scripting languages, software design patterns,
and object-oriented programming
#show_downloads: true
#google_analytics: [Your Google Analytics tracking ID]
remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
